### PR TITLE
added support for unknown triggerpoint when manually invoked

### PR DESCRIPTION
**Pull request by mrkingmarc01**

### CODE REVIEW

**Comment by FrankHeijden** [comment]
lgtm

**Comment by FrankHeijden** [comment]
> missing except keyword!

out of scope for this pr bruh

**Comment by FrankHeijden** [comment]
but ok @mrkingmarc01 make it one mr ig

**Comment by Aekalix** [comment]
> > missing except keyword!
> 
> out of scope for this pr bruh

very true

**Review by FrankHeijden — APPROVED** [review]

**Pull request merged**
